### ISSUE TITLE
how to run on windows ?

### ISSUE THREAD

**Issue by ramstein74** [reingart/rad2py#1]
hello i cloned it but how do i run it ?

Thank you

**Comment by reingart** [comment]
Hi!, please take a look at the documentation (in the google code site):

https://code.google.com/p/rad2py/wiki/InstallationGuide

ASAP I'll try to make a requirements.txt to easy the installation with pip (and include it in the README.md)  
BTW, Are you running windows or linux?
Let me know if you have any further issue,

**Comment by ramstein74** [comment]
running windows 7

**Comment by ramstein74** [comment]
I think you will write a lot of text so a video should be easier to follow
